---

- hosts: jitsi
  remote_user: root
  tasks:
  - name: Upgrading apt
    apt:
      update_cache: true
      allow_unauthenticated: true
      upgrade: true
  - name: Installing HTTPS transport for apt
    apt:
      name: apt-transport-https
      allow_unauthenticated: true
      update_cache: false
  - name: Installing certificates
    apt:
      name: ca-certificates
      allow_unauthenticated: true
      update_cache: false
  
  - name: Adding Repository 
    shell: echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
  - name: Setting Key
    apt_key:
      url: https://download.jitsi.org/jitsi-key.gpg.key
  - name: Upgrading apt
    apt:
      update_cache: true
      allow_unauthenticated: true
      upgrade: true
  - name: Installing Jitsi
    apt:
      name: jitsi-meet
      allow_unauthenticated: true
      update_cache: false
  